# Generated by Django 5.0.7 on 2024-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
